### ISSUE TITLE
Signing Cookies

### ISSUE THREAD

**Issue by elithrar** [justinas/nosurf#11]
nosurf does not currently sign cookies as the standard http.Cookie implementation only defines the "basic" attributes of a cookie.

CSRF cookies should be signed (so we can identify attempts to tamper) with HMAC-SHA256, and then authenticated before checking the cookie against the submitted request. An example of a solid authentication implementation [can be found here](https://github.com/gorilla/securecookie/blob/master/securecookie.go#L126-L262).
- Authenticated cookies should (really) really be the default, but I'm not sure how to reconcile this without breaking the existing API. I would argue that the benefit from authenticating cookie values outweighs the downside of breaking the API. Any major change would be a compile-time error too, and is therefore easier to resolve (no weird gremlins at run-time).
- I would also consider updating the README to stress (as it's extremely important) that package users serve their site over HTTPS (SSL/TLS), as otherwise CSRF tokens are effectively lip service given that the cookies themselves can be hijacked (and as their contents aren't authenticated, changed at whim).
- Encrypted cookies would be an additional "nice to have" but do not really circumvent the need for SSL/TLS. The existing "encryption" references in the docs should also be changed to "masked" or "masking".
- You would facilitate authentication/encryption by allowing a user to pass in keys in a `func (h *CSRFHandler) SetAuthKeys(key []byte, keys ...[]byte)` and `func (h *CSRFHandler) SetEncryptionKeys(key []byte, keys ...[]byte)`, with the variadic param allowing a package user to pass in multiple key pairs (which facilitates cycling keys). This would be similar to how gorilla/securecookie handles key rotation, but you could probably get away with just accepting a single key.
- Leveraging [gorilla/securecookie](https://github.com/gorilla/securecookie) itself may not be a bad idea. You could wrap its exported functions with your own to maintain as much of your existing API as possible, or have `nosurf.New` accept an options struct that then calls securecookie API before then returning a configured `*CSRFHandler`.
- I'd also suggest bringing the default expiry way down to something like a week, tops. Even a day would be fine—users don't take a day to fill out a form.

**Comment by justinas** [comment]
Well this has been sitting open for a while.

Seeing how there are now alternatives like goji-csrf which do use cookie signing and the fact that it would change the API, I think this should be considered out of scope for now.
