### ISSUE TITLE
Cookie tokens not masked?

### ISSUE THREAD

**Issue by paulbellamy** [justinas/nosurf#16]
It seems like the tokens sent out in cookies are never masked. They are masked before being stored in the context, but then the unmasked token is sent out in the cookie. That seems incorrect to me, but I'm not a crypto expert.

This is based trying to use this library, and based on reading: https://github.com/justinas/nosurf/blob/master/handler.go#L182

**Comment by Xeoncross** [comment]
@justinas where is the pad randomized for every request? [I couldn't find it](https://github.com/justinas/nosurf/blob/e51517007dc9daa543fc05e7d63f2636815757a3/handler.go#L116-L181)
