### ISSUE TITLE
Failure with enctype="multipart/form-data"

### ISSUE THREAD

**Issue by bryanjeal** [justinas/nosurf#26]
I cannot get nosurf to work with enctype="multipart/form-data"

The failure error I get is this:
The CSRF token in the cookie doesn't match the one received in a form/header.

Here is the simple.go example modified to use enctype="multipart/form-data"
https://gist.github.com/bryanjeal/448cc89b30643f610315

**Comment by justinas** [comment]
Nice catch, d00541e should've fixed it.

**Comment by bryanjeal** [comment]
Awesome. Thank you for fixing this!

I am not going to lie - I thought it might have been something I was doing wrong.
