### ISSUE TITLE
Why is the token base64 encoded?

### ISSUE THREAD

**Issue by jorgeolivero** [justinas/nosurf#33]
Mostly curious. Wondering what level of security this extra obfuscation brings.

**Comment by elithrar** [comment]
base64 doesn't provide any security here: it's used so that the bytes generated from `crypto/rand` are encoded to ASCII, which effectively makes them printable (and allowable) characters in a cookie and HTML document.

**Comment by justinas** [comment]
^ what @elithrar said. It's basically a universal practice for encoding binary data in cookies. Just check out GitHub's cookies: session data is encoded in base64 (or something really similar).

Hope that helps!

**Comment by jorgeolivero** [comment]
Appreciate the info guys, closing
