### ISSUE TITLE
Send a response body in defaultFailureHandler

### ISSUE THREAD

**Issue by alexedwards** [justinas/nosurf#41]
Would it be possible to change the `defaultFailureHandler` so it includes a basic response body? Something like:

```
func defaultFailureHandler(w http.ResponseWriter, r *http.Request) {
	http.Error(w, http.StatusText(FailureCode), FailureCode)
}
```

Instead of the current `http.Error(w, "", FailureCode)`.

Using `http.StatusText()` wouldn't leak any extra useful information to an attacker, but it would be a nicer and less confusing user (and developer) experience than just seeing a blank page on failure.

I'm very happy to send a PR for this, if you like.

**Comment by justinas** [comment]
Great idea. A PR would be appreciated.

**Comment by justinas** [comment]
Did not close automatically after merging #42 for some reason. Closing.
