### ISSUE TITLE
please consider updating tags or deleting the current tag

### ISSUE THREAD

**Issue by jolan** [justinas/nosurf#43]
My co-worker and I were attempting to use nosurf for something.  We encountered some issues and once we started looking at them we realized glide picked up the 0.1 tag from 4 years ago rather than tip.

Not a big deal since we should have looked more closely when we added the dep via glide but please consider tagging stables release more frequently or removing the existing tag.

**Comment by justinas** [comment]
Thanks for bringing this to my attention. At the time I initially created nosurf, there *was no* Glide :)

I assume the problem is that if Glide finds tags in the repo, it uses the latest one as defined by Semver, rather than just pinning to master?

**Comment by jolan** [comment]
Yep that is exactly what is going on.

**Comment by justinas** [comment]
@jolan Sorry for the delay. I have deleted the `0.1` tag for now. I will think about using semver, but for now, there will be no versioning. At least that's better than a single stale version.

Hope that helps!
