### ISSUE TITLE
Is this normal behavior?

### ISSUE THREAD

**Issue by NCSantos** [justinas/nosurf#59]
Hi,

Thanks for this great package.

To test this I did the following, I'm using JSON on the responses and requests:

I have 2 handlers, both on root "/", one is a GET and the other a POST.
On the GET I only return a token.
On the POST I verify the token and send a new one, like:
```
...
        // Get token from JSON into jd.

	tkn := nosurf.Token(r)
	if !nosurf.VerifyToken(tkn, jd.Token) {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte(`{"message":"Different tokens"}`))
		return
	}

        // Send the new token.
	w.Write([]byte(fmt.Sprintf(`{"token":"%s"}`, tkn)))
```

What I would like to know if it is the normal behavior is that after getting
the token from the GET I can do all the requests to POST with that first token
that it always validates ok. I can even do e.g. 10 request to POST with the
first token, next do another request to POST with the newest token sent by
POST, then again start using the first token and it still validates.

Thanks for your help.

**Comment by justinas** [comment]
Hi @NCSantos,

The token is only regenerated when the cookie either expires (after 365 days by default), is deleted, or corrupted (i.e. token can not be decoded from the cookie). What you see changing every time is the masked token: 32 byte random key and 32 byte `encrypt(key, token)` payload. The unencrypted token stays the same for a long time and thus can be reused.

As long as the third party website can not acquire any of the tokens, this seems fine.

See [this part in token.go](https://github.com/justinas/nosurf/blob/842926618ec724f54d1bafa2a30a527f05eb9d38/token.go#L15-L30) and [this part in handler.go](https://github.com/justinas/nosurf/blob/842926618ec724f54d1bafa2a30a527f05eb9d38/handler.go#L120-L132).

Hope that answers your question.

**Comment by NCSantos** [comment]
Hi @justinas ,

When calling the GET also regenerate the token, e.g.:
Call GET, call POST with token from GET, call GET again, call POST with token from first GET is not valid.

**Comment by justinas** [comment]
I think you are misunderstanding what actually happens. The token in the cookie is unmasked, you can check it: it should not change whether you GET or POST as many times as you'd like. This is the value we care about. The thing that changes is the token for the forms (masked). To be more exact, this token's masking key is regenerated on every request, but the same token is masked every time.

Nosurf does not aim to prevent guarantees from double-submit of requests.

**Comment by NCSantos** [comment]
I am using `curl` to do the requests and was not correctly sending and saving the cookies.
Thanks for your help.

**Comment by justinas** [comment]
No problem, please re-open the issue if you encounter such troubles again.
