### ISSUE TITLE
CSRF failed with bad request

### ISSUE THREAD

**Issue by hoang408** [justinas/nosurf#69]
I am following Trevor Sawler's Golang course, and hit a roadblock with section 8.2.  I have detailed the issue [here](https://stackoverflow.com/questions/75713085/golang-post-failed-nosurf-csrf).  Could someone please help me out?  I have followed the instructions carefully, but it doesn't work as seen in the video.  Many thanks!

**Comment by justinas** [comment]
Your `csrf_token` input field is defined *outside* of the form:

```html
        <!-- from templatedata.go -->
        <input type="text" name="csrf_token" value="{{.CsrfToken}}">
        
        <!-- Second date picker -->
        <form action="/search-availability" method="post" class="needs-validation" novalidate id="date-picker">            
```

and as such is *not* being sent with the request:

![image](https://user-images.githubusercontent.com/662666/224567876-fe1935b9-dcff-492a-a658-d3dc5592f7af.png)


`nosurf` rightly denies this request.
