### ISSUE TITLE
Validation fails with X-CSRF-Token

### ISSUE THREAD

**Issue by danjac** [justinas/nosurf#7]
I'm only able to get a 400 Bad Request with POST/DELETE requests to my REST application.

Running an app in localhost I have this value in my csrf_token cookie:
0bYcWmFvvMpZXMSgau2Jx3uxQGhyfEtTxOEC6zrtlfs=

And the value passed back in X-CSRF-Token:
0bYcWmFvvMpZXMSgau2Jx3uxQGhyfEtTxOEC6zrtlfs=

My set up:

```
http.Handle("/", nosurf.New(myRoutes))
http.ListenAndServe(":"+port, nil)
```

I had this working fine until a recent go get update, so some kind of regression maybe?

**Comment by yktoo** [comment]
Well, apparently this is not going to work with Angular as it sends back in the Header exactly what it collected from the cookie.

I'm actually missing the point of modifying the token on each request, and so are the Angular authors apparently. The fact the token can *only* be generated on the backend makes it, sadly, a no-go for AJAX apps. Unless I'm overlooking something here.

**Comment by justinas** [comment]
> Well, apparently this is not going to work with Angular as it sends back in the Header exactly what it collected from the cookie.

Is this some built-in functionality of Angular? I am afraid we can not adjust to every framework's way of doing things. However, in general this is a solved issue, and other frameworks recommend doing a similar thing:

```
<script>
window.csrfToken = "{{ .Token }}";
</script>
```
in your Go template, then use it as necessary. You should be able to re-submit the same token multiple times.

**Comment by yktoo** [comment]
Thanks a bunch for your advice!

Yes, it is the [standard behaviour](https://angular.io/guide/http#security-xsrf-protection) of Angular, so one will need to alter that flow to collect the token from a variable and add it as a header.
